apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: jaeger
          name: trace_id

        - url: http://jaeger-all-in-one:16686/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI

  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger-all-in-one:16686
    editable: true
    isDefault: false

  - name: opensearch-cluster
    uid: opensearch
    type: elasticsearch
    access: proxy
    url: http://opensearch-cluster:9200
    editable: true
    isDefault: false
    jsonData:
      interval: ''
      timeField: '@timestamp'
      esVersion: '8.0.0'
      logMessageField: _source
      logLevelField: Attributes.level
      dataLinks:
        - datasourceUid: jaeger
          field: Attributes.trace_id
          url: '$${__value.raw}'
